# -*- coding: utf-8 -*-
"""Emotion_Detection_using_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ6rnz3dzHGzFFQaNxlcZdS3t-ehae2n

##**1.Environment Setup**

####Using Google Collab for Training

####Installing Libraries
"""

!pip install numpy pandas scikit-learn matplotlib seaborn tensorflow keras transformers

"""##**2.Importing Libraries**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

"""##**3.Loading Dataset Files**

####Loading Kaggle emotion dataset (train, test, validation)
"""

train_df = pd.read_csv("train.txt", sep=";", names=["text", "emotion"])
test_df = pd.read_csv("test.txt", sep=";", names=["text", "emotion"])
val_df = pd.read_csv("val.txt", sep=";", names=["text", "emotion"])

print(train_df.head())

"""##**4.Preprocessing**

####Combine train + validation then convert to numerical features
"""

full_train = pd.concat([train_df, val_df])

X_train = full_train['text']
y_train = full_train['emotion']

X_test = test_df['text']
y_test = test_df['emotion']

"""####TF-IDF vectorization"""

vectorizer = TfidfVectorizer(max_features=10000)
X_train_vec = vectorizer.fit_transform(X_train).toarray()
X_test_vec = vectorizer.transform(X_test).toarray()

"""####Encode labels"""

y_train_encoded = pd.get_dummies(y_train).values
y_test_encoded = pd.get_dummies(y_test).values

"""##**5.Model**

####Building a simple Neural Network with multiple hidden layers
"""

model = Sequential([
    Dense(1024, activation='relu', input_shape=(X_train_vec.shape[1],)),
    Dropout(0.5),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(y_train_encoded.shape[1], activation='softmax')
])

"""##**6.Training**

####Training the model for 20 epochs, batch size 32
"""

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_vec, y_train_encoded,
                    epochs=20, batch_size=32,
                    validation_data=(X_test_vec, y_test_encoded))

"""##**7.Evaluation**

####Evaluating model performance: precision, recall, F1‑score, and confusion matrix.
"""

y_pred = model.predict(X_test_vec)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test_encoded, axis=1)

print(classification_report(y_true, y_pred_classes))

sns.heatmap(confusion_matrix(y_true, y_pred_classes), annot=True, fmt='d')
plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted Emotion")
plt.ylabel("Actual Emotion")
plt.show()

"""####Dataset distribution

######Distribution of emotions in training data.
"""

sns.countplot(x='emotion', data=train_df)
plt.title("Distribution of Emotions in Training Data")
plt.show()

"""####Training Accuracy & Loss

######Training progress: accuracy and loss curves.
"""

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""####Prediction Histogram

######Predicted emotion counts by the model.
"""

pred_labels = [list(pd.get_dummies(y_train).columns)[i] for i in y_pred_classes]
sns.countplot(x=pred_labels)
plt.title("Predicted Emotion Counts")
plt.show()

"""##**Bonus Demo**

###Run Hugging Face pipeline live.

######Quick demo with pre‑trained model for instant text emotion detection
"""

from transformers import pipeline

# Load pre-trained emotion model
emotion_model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

# Ask user for input
user_text = input("Enter a sentence to analyze emotion: ")
print(emotion_model(user_text))

while True:
    user_text = input("Enter a sentence (or type 'exit' to quit): ")
    if user_text.lower() == 'exit':
        break
    print(emotion_model(user_text))